services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: echo srvr | nc localhost 2181 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      # Mapeia a porta 9092 do seu PC para a 29092 do container (listener externo)
      - "9092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Define explicitamente onde o Kafka deve "escutar" dentro do container
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      # Define como os clientes devem encontrar o Kafka
      # PLAINTEXT: Para backend/simulador (dentro do docker) -> kafka:9092
      # PLAINTEXT_HOST: Para vocÃª/browser (fora do docker) -> localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      # Verifica a porta interna (9092)
      test: nc -z localhost 9092 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  backend:
    build: 
      context: ./modulos/visualizar/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./modulos/visualizar/backend:/app
    environment:
      # Backend continua usando a porta interna 9092
      KAFKA_BROKER: kafka:9092

  frontend:
    build:
      context: ./modulos/visualizar/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./modulos/visualizar/frontend:/app
      - /app/node_modules

  simulador:
    build:
      context: ./modulos/simulador
      dockerfile: Dockerfile
    environment:
      # Simulador continua usando a porta interna 9092
      - KAFKA_BROKER=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    restart: "no"

  cruzamento:
    build:
      context: ./modulos
      dockerfile: ./cruzamento/Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_APPLICATION_NAME: cruzamento
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  orquestrador:
    build:
      context: ./modulos
      dockerfile: ./orquestrador/Dockerfile
    ports:
      - "8082:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_APPLICATION_NAME: orquestrador
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped